import { Injectable } from '@angular/core';

@Injectable()
export class ProductsService {
  sections: Array<any> = [{id:1, name:'sandwichs', products: [{id: 1, name: 'los leños'},
                                                              {id: 2, name: 'campesino'},
                                                              {id: 3, name: 'chacarero'},
                                                              {id: 4, name: 'universitario'},
                                                              {id: 5, name: 'napolitano'},
                                                              {id: 6, name: 'frances'},
                                                              {id: 7, name: 'barros luco'},
                                                              {id: 8, name: 'vegetariano'},
                                                              {id: 9, name: 'italiano'},
                                                            ]},
                          {id:2, name:'pichangas', products: [{id:10, name: 'para 1 persona'},
                                                             {id:11, name: 'para 2 personas'},
                                                             {id:12, name: 'para 3 personas'},
                                                            ]},
                          {id:3, name:'pizzas', products: [{id: 13, name: 'los leños'},
                                                           {id: 14, name: 'cazadora'},
                                                           {id: 15, name: 'francesa'},
                                                           {id: 16, name: 'española'},
                                                           {id: 17, name: 'napolitana'},
                                                           {id: 18, name: 'vegetariana'},
                                                           {id: 19, name: 'marinera'},
                                                          ]},
                          {id:4, name:'entradas', products: [{id: 13, name: 'camarones en salsa verde'},
                                                           {id: 14, name: 'choritos en salsa verde'},
                                                           {id: 15, name: 'palta reina (rellena con pollo)'},
                                                           {id: 16, name: 'palta york (Rellena con jamón)'},
                                                          ]},
                          {id:5, name:'platos a lo pobre', products: [{id: 13, name: 'filete a lo pobre'},
                                                           {id: 14, name: 'lomo a lo pobre'},
                                                           {id: 15, name: 'entrecot a lo pobre'},
                                                           {id: 16, name: 'escalopa kaiser a lo pobre'},
                                                           {id: 17, name: 'bistec a lo pobre'},
                                                           {id: 18, name: 'chiletas a lo pobre'},
                                                           {id: 19, name: 'pollo asado a lo pobre'},
                                                           {id: 17, name: 'filete solo'},
                                                           {id: 17, name: 'lomo solo'},
                                                           {id: 17, name: 'entrecot solo'},
                                                           {id: 17, name: 'escalopa kaiser sola'},
                                                           {id: 17, name: 'asado vacuno solo'},
                                                           {id: 17, name: 'bistec solo'},
                                                           {id: 17, name: 'chuletas sola'},
                                                           {id: 17, name: 'pollo asado solo'},
                                                           {id: 17, name: 'pollo a la plancha'},
                                                           {id: 17, name: 'salmón a la plancha'},
                                                           {id: 17, name: 'salmón milanés'},
                                                           {id: 17, name: 'salsa leños'},
                                                           {id: 17, name: 'salsa de champiñones'},
                                                           {id: 17, name: 'salsa de camarones'},
                                                           {id: 17, name: 'salsa a la pimienta'},
                                                          ]},
                          {id:6, name:'platos extras', products: [{id: 2, name: 'costilla de cerdo asado con pure chileno'},
                                                                  {id: 3, name: 'filete los leños'},
                                                                  {id: 4, name: 'lomo e entrecot los leños'}]},
                          {id:7, name:'agregados', products: [{id: 1, name: 'puré chileno'},
                                                              {id: 2, name: 'puré picante'},
                                                              {id: 2, name: 'papas duquesas'},
                                                              {id: 2, name: 'papas fritas'},
                                                              {id: 2, name: 'puré'},
                                                              {id: 2, name: 'arroz'},
                                                              {id: 2, name: 'papas al vapor'},
                                                              ]},
                          {id:8, name:'ensaladas', products: [{id:2, name: 'los leños'},
                                                              {id: 3, name: 'cazadora'},
                                                              {id: 3, name: 'chilena'},
                                                              {id: 3, name: 'palmito-palta'},
                                                              {id: 3, name: 'maiz-mayonesa'},
                                                              {id: 3, name: 'surtido'},
                                                              {id: 3, name: 'mixta'},
                                                            ]},
                          {id:9, name:'postres', products: [{id: 1, name:'copa los leños'},
                                                            {id: 1, name:'copa primavera'},
                                                            {id: 1, name:'banana split'},
                                                            {id: 1, name:'café helado'},
                                                            {id: 1, name:'copa helada'},
                                                            {id: 1, name:'murta con membrillo'},
                                                            {id: 1, name:'papayas al jugo'},
                                                            {id: 1, name:'macedonia de frutas'},
                                                            {id: 1, name:'frutillas en almibar'},
                                                            {id: 1, name:'porción de crema'},
                                                            ]},
                          {id:10, name:'bebidas calientes', products: [{id:1,name: 'chocolate caliente'},
                                                                      {id: 1,name: 'café con leche'},
                                                                      {id: 1,name: 'café instantáneo'},
                                                                      {id: 1,name: 'té hierbas'},
                                                                      {id: 1,name: 'té'},
                                                                      {id: 1,name: 'té verde'},
                                                                      {id: 1,name: 'té rojo'},
                                                                      {id: 1,name: 'té con canela'},
                                                                    ]},
                          {id:11, name:'bebidas frias', products: [{id:1,name:'bebida individual'},
                                                                    {id:2,name: 'jugo natural'},
                                                                    {id:2,name: 'vaso jugo'},
                                                                    {id:2,name: 'jarra jugo natural'},
                                                                  ]},
                          {id:12, name:'cervezas', products: [{id:1,name:'gran torobayo'},
                                                                    {id:2,name: 'kunstmann anwanter'},
                                                                    {id:2,name: 'kunstmann sin filtrar'},
                                                                    {id:2,name: 'kunstmann sin alcohol'},
                                                                    {id:2,name: 'kunstmann de miel'},
                                                                    {id:2,name: 'kunstmann de arándano'},
                                                                    {id:2,name: 'kunstmann de trigo'},
                                                                    {id:2,name: 'kunstmann torobayo'},
                                                                    {id:2,name: 'kunstmann lagger'},
                                                                    {id:2,name: 'kunstmann bock'},
                                                                    {id:2,name: 'cuello negro'},
                                                                    {id:2,name: 'selva fria'},
                                                                    {id:2,name: 'entrerios'},
                                                                    {id:2,name: 'valbier'},
                                                                    {id:2,name: 'bundor'},
                                                                    {id:2,name: 'los torreones'},
                                                                  ]},
                          {id:13, name:'schop kunstmann', products: [{id:1,name: 'gran torobayo'},
                                                                      {id:2,name: 'lagger sin filtrar'},
                                                                      {id:2,name: 'anwanter'},
                                                                      {id:2,name: 'torobayo'},
                                                                      {id:2,name: 'lagger'},
                                                                      {id:2,name: 'bock'},
                                                                      {id:2,name: 'micheladas'},
                                                                      {id:2,name: 'corto jugo limón'},
                                                                    ]},
                          {id:14, name:'tragos', products: [{id:1,name: 'mango sour'},
                                                                      {id:2,name: 'jerez sour'},
                                                                      {id:2,name: 'pisco sour'},
                                                                      {id:2,name: 'amaretto sour'},
                                                                      {id:2,name: 'vodka sour'},
                                                                      {id:2,name: 'tequila sour'},
                                                                      {id:2,name: 'whisky sour'},
                                                                      {id:2,name: 'tequila margarita'},
                                                                      {id:2,name: 'tequila sunrise'},
                                                                      {id:2,name: 'tequila blue'},
                                                                      {id:2,name: 'daikiri frambuesa'},
                                                                      {id:2,name: 'daikiri frutilla'},
                                                                      {id:2,name: 'daikiri plátano'},
                                                                      {id:2,name: 'daikiri durazno'},
                                                                      {id:2,name: 'daikiri piña'},
                                                                      {id:2,name: 'vodka naranja'},
                                                                      {id:2,name: 'ruso blanco'},
                                                                      {id:2,name: 'ruso negro'},
                                                                      {id:2,name: 'vaina'},
                                                                      {id:2,name: 'piña colada'},
                                                                      {id:2,name: 'caipiriña'},
                                                                      {id:2,name: 'caipiroska'},
                                                                      {id:2,name: 'tom collins'},
                                                                      {id:2,name: 'jhon collins'},
                                                                      {id:2,name: 'primavera con licor'},
                                                                      {id:2,name: 'primavera sin licor'},
                                                                      {id:2,name: 'bitter batido'},
                                                                      {id:2,name: 'bitter a la francesa'},
                                                                      {id:2,name: 'sangria en jerez'},
                                                                    ]},
                          {id:15, name:'whisky'},
                          {id:16, name:'vinos'},
                        ]

  constructor() { }

  getSections() {
    return this.sections;
  }

}
