import { Injectable } from '@angular/core';

@Injectable()
export class ProductsService {
  public sections: Array<any> = [{id:1, name:'sandwichs', products: [{id: 1, name: 'los leños', img: 'product'},
                                                              {id: 2, name: 'campesino', img: 'product'},
                                                              {id: 3, name: 'chacarero', img: 'product'},
                                                              {id: 4, name: 'universitario', img: 'product'},
                                                              {id: 5, name: 'napolitano', img: 'product'},
                                                              {id: 6, name: 'frances', img: 'product'},
                                                              {id: 7, name: 'barros luco', img: 'product'},
                                                              {id: 8, name: 'vegetariano', img: 'product'},
                                                              {id: 9, name: 'italiano', img: 'product'},
                                                            ]},
                          {id:2, name:'pichangas', products: [{id:10, name: 'para 1 persona', img: 'product'},
                                                             {id:11, name: 'para 2 personas', img: 'product'},
                                                             {id:12, name: 'para 3 personas', img: 'product'},
                                                             {id:12, name: 'para 4 personas', img: 'product'},
                                                            ]},
                          {id:3, name:'pizzas', products: [{id: 13, name: 'los leños', img: 'product'},
                                                           {id: 14, name: 'cazadora', img: 'product'},
                                                           {id: 15, name: 'francesa', img: 'product'},
                                                           {id: 16, name: 'española', img: 'product'},
                                                           {id: 17, name: 'napolitana', img: 'product'},
                                                           {id: 18, name: 'vegetariana', img: 'product'},
                                                           {id: 19, name: 'marinera', img: 'product'},
                                                          ]},
                          {id:4, name:'entradas', products: [{id: 13, name: 'camarones en salsa verde', img: 'product'},
                                                           {id: 14, name: 'choritos en salsa verde', img: 'product'},
                                                           {id: 15, name: 'palta reina (rellena con pollo)', img: 'product'},
                                                           {id: 16, name: 'palta york (Rellena con jamón)', img: 'product'},
                                                          ]},
                          {id:5, name:'platos a lo pobre', products: [{id: 13, name: 'filete a lo pobre', img: 'product'},
                                                           {id: 14, name: 'lomo a lo pobre', img: 'product'},
                                                           {id: 15, name: 'entrecot a lo pobre', img: 'product'},
                                                           {id: 16, name: 'escalopa kaiser a lo pobre', img: 'product'},
                                                           {id: 17, name: 'bistec a lo pobre', img: 'product'},
                                                           {id: 18, name: 'chiletas a lo pobre', img: 'product'},
                                                           {id: 19, name: 'pollo asado a lo pobre', img: 'product'},
                                                           {id: 17, name: 'filete solo', img: 'product'},
                                                           {id: 17, name: 'lomo solo', img: 'product'},
                                                           {id: 17, name: 'entrecot solo', img: 'product'},
                                                           {id: 17, name: 'escalopa kaiser sola', img: 'product'},
                                                           {id: 17, name: 'asado vacuno solo', img: 'product'},
                                                           {id: 17, name: 'bistec solo', img: 'product'},
                                                           {id: 17, name: 'chuletas sola', img: 'product'},
                                                           {id: 17, name: 'pollo asado solo', img: 'product'},
                                                           {id: 17, name: 'pollo a la plancha', img: 'product'},
                                                           {id: 17, name: 'salmón a la plancha', img: 'product'},
                                                           {id: 17, name: 'salmón milanés', img: 'product'},
                                                           {id: 17, name: 'salsa leños', img: 'product'},
                                                           {id: 17, name: 'salsa de champiñones', img: 'product'},
                                                           {id: 17, name: 'salsa de camarones', img: 'product'},
                                                           {id: 17, name: 'salsa a la pimienta', img: 'product'},
                                                          ]},
                          {id:6, name:'platos extras', products: [{id: 2, name: 'costilla de cerdo asado con pure chileno', img: 'product'},
                                                                  {id: 3, name: 'filete los leños', img: 'product'},
                                                                  {id: 4, name: 'lomo e entrecot los leños'}], img: 'product'},
                          {id:7, name:'agregados', products: [{id: 1, name: 'puré chileno', img: 'product'},
                                                              {id: 2, name: 'puré picante', img: 'product'},
                                                              {id: 2, name: 'papas duquesas', img: 'product'},
                                                              {id: 2, name: 'papas fritas', img: 'product'},
                                                              {id: 2, name: 'puré', img: 'product'},
                                                              {id: 2, name: 'arroz', img: 'product'},
                                                              {id: 2, name: 'papas al vapor', img: 'product'},
                                                              ]},
                          {id:8, name:'ensaladas', products: [{id:2, name: 'los leños', img: 'product'},
                                                              {id: 3, name: 'cazadora', img: 'product'},
                                                              {id: 3, name: 'chilena', img: 'product'},
                                                              {id: 3, name: 'palmito-palta', img: 'product'},
                                                              {id: 3, name: 'maiz-mayonesa', img: 'product'},
                                                              {id: 3, name: 'surtido', img: 'product'},
                                                              {id: 3, name: 'mixta', img: 'product'},
                                                            ]},
                          {id:9, name:'postres', products: [{id: 1, name:'copa los leños', img: 'product'},
                                                            {id: 1, name:'copa primavera', img: 'product'},
                                                            {id: 1, name:'banana split', img: 'product'},
                                                            {id: 1, name:'café helado', img: 'product'},
                                                            {id: 1, name:'copa helada', img: 'product'},
                                                            {id: 1, name:'murta con membrillo', img: 'product'},
                                                            {id: 1, name:'papayas al jugo', img: 'product'},
                                                            {id: 1, name:'macedonia de frutas', img: 'product'},
                                                            {id: 1, name:'frutillas en almibar', img: 'product'},
                                                            {id: 1, name:'porción de crema', img: 'product'},
                                                            ]},
                          {id:10, name:'bebidas calientes', products: [{id:1,name: 'chocolate caliente', img: 'product'},
                                                                      {id: 1,name: 'café con leche', img: 'product'},
                                                                      {id: 1,name: 'café instantáneo', img: 'product'},
                                                                      {id: 1,name: 'té hierbas', img: 'product'},
                                                                      {id: 1,name: 'té', img: 'product'},
                                                                      {id: 1,name: 'té verde', img: 'product'},
                                                                      {id: 1,name: 'té rojo', img: 'product'},
                                                                      {id: 1,name: 'té con canela', img: 'product'},
                                                                    ]},
                          {id:11, name:'bebidas frias', products: [{id:1,name:'bebida individual', img: 'product'},
                                                                    {id:2,name: 'jugo natural', img: 'product'},
                                                                    {id:2,name: 'vaso jugo', img: 'product'},
                                                                    {id:2,name: 'jarra jugo natural', img: 'product'},
                                                                  ]},
                          {id:12, name:'cervezas', products: [{id:1,name:'gran torobayo', img: 'product'},
                                                                    {id:2,name: 'kunstmann anwanter', img: 'product'},
                                                                    {id:2,name: 'kunstmann sin filtrar', img: 'product'},
                                                                    {id:2,name: 'kunstmann sin alcohol', img: 'product'},
                                                                    {id:2,name: 'kunstmann de miel', img: 'product'},
                                                                    {id:2,name: 'kunstmann de arándano', img: 'product'},
                                                                    {id:2,name: 'kunstmann de trigo', img: 'product'},
                                                                    {id:2,name: 'kunstmann torobayo', img: 'product'},
                                                                    {id:2,name: 'kunstmann lagger', img: 'product'},
                                                                    {id:2,name: 'kunstmann bock', img: 'product'},
                                                                    {id:2,name: 'cuello negro', img: 'product'},
                                                                    {id:2,name: 'selva fria', img: 'product'},
                                                                    {id:2,name: 'entrerios', img: 'product'},
                                                                    {id:2,name: 'valbier', img: 'product'},
                                                                    {id:2,name: 'bundor', img: 'product'},
                                                                    {id:2,name: 'los torreones', img: 'product'},
                                                                  ]},
                          {id:13, name:'schop kunstmann', products: [{id:1,name: 'gran torobayo', img: 'product'},
                                                                      {id:2,name: 'lagger sin filtrar', img: 'product'},
                                                                      {id:2,name: 'anwanter', img: 'product'},
                                                                      {id:2,name: 'torobayo', img: 'product'},
                                                                      {id:2,name: 'lagger', img: 'product'},
                                                                      {id:2,name: 'bock', img: 'product'},
                                                                      {id:2,name: 'micheladas', img: 'product'},
                                                                      {id:2,name: 'corto jugo limón', img: 'product'},
                                                                    ]},
                          {id:14, name:'tragos', products: [{id:1,name: 'mango sour', img: 'product'},
                                                                      {id:2,name: 'jerez sour', img: 'product'},
                                                                      {id:2,name: 'pisco sour', img: 'product'},
                                                                      {id:2,name: 'amaretto sour', img: 'product'},
                                                                      {id:2,name: 'vodka sour', img: 'product'},
                                                                      {id:2,name: 'tequila sour', img: 'product'},
                                                                      {id:2,name: 'whisky sour', img: 'product'},
                                                                      {id:2,name: 'tequila margarita', img: 'product'},
                                                                      {id:2,name: 'tequila sunrise', img: 'product'},
                                                                      {id:2,name: 'tequila blue', img: 'product'},
                                                                      {id:2,name: 'daikiri frambuesa', img: 'product'},
                                                                      {id:2,name: 'daikiri frutilla', img: 'product'},
                                                                      {id:2,name: 'daikiri plátano', img: 'product'},
                                                                      {id:2,name: 'daikiri durazno', img: 'product'},
                                                                      {id:2,name: 'daikiri piña', img: 'product'},
                                                                      {id:2,name: 'vodka naranja', img: 'product'},
                                                                      {id:2,name: 'ruso blanco', img: 'product'},
                                                                      {id:2,name: 'ruso negro', img: 'product'},
                                                                      {id:2,name: 'vaina', img: 'product'},
                                                                      {id:2,name: 'piña colada', img: 'product'},
                                                                      {id:2,name: 'caipiriña', img: 'product'},
                                                                      {id:2,name: 'caipiroska', img: 'product'},
                                                                      {id:2,name: 'tom collins', img: 'product'},
                                                                      {id:2,name: 'jhon collins', img: 'product'},
                                                                      {id:2,name: 'primavera con licor', img: 'product'},
                                                                      {id:2,name: 'primavera sin licor', img: 'product'},
                                                                      {id:2,name: 'bitter batido', img: 'product'},
                                                                      {id:2,name: 'bitter a la francesa', img: 'product'},
                                                                      {id:2,name: 'sangria en jerez', img: 'product'},
                                                                      {id:2,name: 'combinado en bitter', img: 'product'},
                                                                      {id:2,name: 'combinado en fernet', img: 'product'},
                                                                      {id:2,name: 'martini seco', img: 'product'},
                                                                      {id:2,name: 'martini en las rocas', img: 'product'},
                                                                      {id:2,name: 'manhattan', img: 'product'},
                                                                      {id:2,name: 'old fashion', img: 'product'},
                                                                      {id:2,name: 'clavo oxidado', img: 'product'},
                                                                      {id:2,name: 'baileys', img: 'product'},
                                                                      {id:2,name: 'combinado pisco mistral 35°', img: 'product'},
                                                                      {id:2,name: 'combinado pisco mistral 40°', img: 'product'},
                                                                      {id:2,name: 'combinado alto del carmen 35°', img: 'product'},
                                                                      {id:2,name: 'combinado alto del carmen 40°', img: 'product'},
                                                                      {id:2,name: 'ron havana reserva', img: 'product'},
                                                                      {id:2,name: 'ron havana especial', img: 'product'},
                                                                      {id:2,name: 'ron barceló gran añejo', img: 'product'},
                                                                      {id:2,name: 'ron barceló añejo', img: 'product'},
                                                                      {id:2,name: 'ron abuelo', img: 'product'},
                                                                      {id:2,name: 'ron cacique', img: 'product'},
                                                                      {id:2,name: 'ron pampero', img: 'product'},
                                                                      {id:2,name: 'gin con gin beefeater', img: 'product'},
                                                                      {id:2,name: 'vodka tónica', img: 'product'},
                                                                      {id:2,name: 'combinado vodka stolichnaya', img: 'product'},
                                                                      {id:2,name: 'combinado vodka absolut blue', img: 'product'},
                                                                      {id:2,name: 'combinado vodka absolut sabores', img: 'product'},
                                                                      {id:2,name: 'bajativos', img: 'product'},
                                                                      {id:2,name: 'campari tónica', img: 'product'},
                                                                      {id:2,name: 'campari naranja', img: 'product'},
                                                                      {id:2,name: 'campari soberano', img: 'product'},
                                                                    ]},
                          {id:15, name:'whisky', products: [{id:1,name: 'chivas regal (12 años)', img: 'product'},
                                                            {id:2,name: 'jhonny walker green label (12 años)', img: 'product'},
                                                            {id:2,name: 'jhonny walker black label (12 años)', img: 'product'},
                                                            {id:2,name: 'jhonny walker red label (12 años)', img: 'product'},
                                                            {id:2,name: 'jack daniels', img: 'product'},
                                                            {id:2,name: 'ballantines', img: 'product'},
                                                            {id:2,name: 'sandy macdonald', img: 'product'},
                                                            {id:2,name: 'white horse', img: 'product'},
                                                          ]},
                          {id:16, name:'vinos', products: [{id:1,name: 'casa real 3/4', img: 'product'},
                                                            {id:2,name: 'medalla real 3/4', img: 'product'},
                                                            {id:2,name: '120 reserva especial 3/4', img: 'product'},
                                                            {id:2,name: '120 3 medallas 3/4', img: 'product'},
                                                            {id:2,name: 'savignon blanc 1/2', img: 'product'},
                                                            {id:2,name: 'carmen margaux 3/4', img: 'product'},
                                                            {id:2,name: 'casillero del diablo 3/4', img: 'product'},
                                                            {id:2,name: 'santa emiliana 3/4', img: 'product'},
                                                            {id:2,name: 'misiones de rengo 3/4', img: 'product'},
                                                            {id:2,name: 'misiones de rengo personal', img: 'product'},
                                                          ]},
                        ]

  constructor() { }

  getSections() {
    return this.sections;
  }

}
